<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ERSCLauncher</AssemblyName>
    <Version>1.2.0</Version>
    <FileVersion>1.2.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ERSC.Launcher.Core/ERSC.Launcher.Core.csproj" />
  </ItemGroup>
</Project>
